apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: websolla
build:
  artifacts:
  - image: docker.pkg.github.com/sealtv/http-swagger-hello-world/hw
    context: .
    docker:
      dockerfile: ./Dockerfile

    # custom:
    #   buildCommand: ./build.sh
    #   dependencies:
    #     paths:
    #     - pkg/**
    #     - src/*.go
    #     ignore:
    #     - vendor/**
# deploy:
#   kubectl:
#     manifests:
#     - websolla_deployment.yaml
