apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: http-swagger-hello-world
build:
  artifacts:
  - image: docker.pkg.github.com/sealtv/http-swagger-hello-world/hw
    context: .
    docker:
      dockerfile: ./Dockerfile
# deploy:
#   kubectl:
#     manifests:
#     - deployment.yaml
